"""Zero-shot forecasting and scenario preference ranking for GGG simulator trajectories.

This package forecasts trajectories generated by the local simulator, reports
point accuracy and interval coverage under frozen TimesFM 3 inference, and ranks
scenarios by GGG preference scores applied to forecast distributions.
"""
